### ISSUE TITLE
Warning Message when using update interval

### ISSUE THREAD

**Issue by Campbellked** [bitfocus/companion-module-christie-projector#11]
When I leave the "update interval" to default, 5000 I keep getting an error message that says "warning" and the connection status turns red. When I set this to zero everything seems to be ok. I can power on and off the projectors but do I need the "update interval" to keep checking status?

**Comment by josephdadams** [comment]
You need the update interval status to check for the latest data every 5000ms or you won't have accurate data from the device. Setting it to 0 means it doesn't run at all.

In the latest version, I removed the part that changed the instance status to Warning, and just log the error instead.
