### ISSUE TITLE
Christie not powering off

### ISSUE THREAD

**Issue by mick76hd** [bitfocus/companion-module-christie-projector#2]
The Power ON command works for our Christie WU12K. The Power OFF command, however, does not.

**Comment by McHauge** [comment]
@mick76hd what does the power off do? nothing at all? be aware that the power off option is only power down to standby and can take up to 5 minutes do to the cooldown time of the lamp in the projector

**Comment by mick76hd** [comment]
Thanks for the follow up. The power off command does nothing that I can see. I tried hitting it twice to see if was a Standby or double button press type thing to power off. It just seems to have no effect. The On Command works perfectly.

Mickey Lyons
Director of Technical Ministries

[cid:image002.jpg@01D22F93.37C2B190]

770.380.5852
mlyons@mountpisgah.org<mailto:mlyons@mountpisgah.org> | mountpisgah.org<http://mountpisgah.org>

On Nov 5, 2019, at 3:57 AM, Andreas Thomsen <notifications@github.com<mailto:notifications@github.com>> wrote:


@mick76hd<https://github.com/mick76hd> what does the power off do? nothing at all? be aware that the power off option is only power down to standby and can take up to 5 minutes do to the cooldown time of the lamp in the projector

**Comment by McHauge** [comment]
@mick76hd I'm currently working on expanding this module, and would you be able to test if the shutter and power button work in a test build. it can be run without an install on windows, you can find it at this link:
[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by McHauge** [comment]
@mick76hd Hi, again, just added some feedback options to the module and if you had a chance to test it that would be awesome, you can find a compiled version at the link above. you might need to press some buttons to get the feedback to run. Still, need to set up some way to collect current values at startup.

-McHauge

**Comment by mick76hd** [comment]
Just tested it. Off now works and so does shutter. Thanks!

Mickey Lyons | Technical Director
Mount Pisgah United Methodist Church
c. 770.380.5852<tel:770.380.5852>
e. mlyons@mountpisgah.org<mailto:mlyons@mountpisgah.org>
w. mountpisgah.org<http://www.mountpisgah.org/>

On Nov 8, 2019, at 7:56 PM, Andreas Thomsen <notifications@github.com> wrote:

﻿

@mick76hd<https://github.com/mick76hd> Hi, again, just added some feedback options to the module and if you had a chance to test it that would be awesome, you can find a compiled version at the link above. you might need to press some buttons to get the feedback to run. Still, need to set up some way to collect current values at startup.

-McHauge

**Comment by McHauge** [comment]
@mick76hd that's awesome to hear how about the feedbacks do they react as expected? first time doing feedback so not to sure myself 

-Andreas

**Comment by mick76hd** [comment]
I’m not sure I understand what feedbacks are. I just setup the ON and Off Commands with 3 IP addresses of Projectors to turn them all on and off together. I setup an quick button with a Toggle on it to test the shutter.

Mickey Lyons
Director of Technical Ministries

[cid:image002.jpg@01D22F93.37C2B190]
770.380.5852
mlyons@mountpisgah.org<mailto:mlyons@mountpisgah.org> | mountpisgah.org<http://mountpisgah.org>

On Nov 13, 2019, at 3:40 PM, Andreas Thomsen <notifications@github.com<mailto:notifications@github.com>> wrote:


@mick76hd<https://github.com/mick76hd> that's awesome to hear how about the feedbacks do they react as expected? first time doing feedback so not to sure myself

-Andreas

**Comment by McHauge** [comment]
if you are on the build i made today, there should be presets for it, that will change colors depending on the current state

**Comment by McHauge** [comment]
there is a set of monitor presets under the tab 'presets' -> 'status'

**Comment by McHauge** [comment]
![image](https://user-images.githubusercontent.com/31018035/68803048-6b4ba200-065f-11ea-9d17-bb3530ae4c86.png)
![image](https://user-images.githubusercontent.com/31018035/68803105-73a3dd00-065f-11ea-9070-1fb5b179e841.png)

**Comment by McHauge** [comment]
@mick76hd you should be able to just drag and drop them onto the buttons layout, but you need to enable error messages on the projector (preset for it under commands)

**Comment by mick76hd** [comment]
Very cool. I’ll try it out tomorrow.

Mickey Lyons | Technical Director
Mount Pisgah United Methodist Church
c. 770.380.5852<tel:770.380.5852>
e. mlyons@mountpisgah.org<mailto:mlyons@mountpisgah.org>
w. mountpisgah.org<http://www.mountpisgah.org/>

On Nov 13, 2019, at 3:58 PM, Andreas Thomsen <notifications@github.com> wrote:

﻿

@mick76hd<https://github.com/mick76hd> you should be able to just drag and drop them onto the buttons layout, but you need to enable error messages on the projector (preset for it under commands)

**Comment by josephdadams** [comment]
Closing this out as it looks like this is completed.
