### ISSUE TITLE
Lens related commands, feedback and variables doesn't work

### ISSUE THREAD

**Issue by andreaimpact** [bitfocus/companion-module-christie-projector#4]
with v 2.0.3 several command don't work. We tried with both roadster 10k and boxer 30k.
Every lens related command doesn't work for example. 
We compared the commands in the instance code with commands in TIPM serial commands and they seem to be different.

In addiction also feedback and variables doen't work.

Tahnk you
AT

**Comment by josephdadams** [comment]
If you are still experiencing this issue with the latest version of the module, please re-open your issue and add more information about the different commands. Thank you.
