### ISSUE TITLE
[feature request] Feedback support for Christie Projectors

### ISSUE THREAD

**Issue by FrancescoValentiniSTOP** [bitfocus/companion-module-christie-projector#5]
I tested the Christie Projector module with our Christie Boxer and GS Series.

The commands work great (input select, warp select, shutter on/off, etc.) but the feedback don't seem to get the status of the projectors.

I'm mainly interested in the shutter status. Is it something you can implement?

Here is the documentation from the Christie Website.

https://www.christiedigital.com/globalassets/resources/public/020-101697-12-Christie-LIT-TECH-REF-Boxer-4K-API.pdf

https://www.christiedigital.com/globalassets/resources/public/020-101695-04-christie-lit-tech-ref-boxer-4k-status-system.pdf

https://www.christiedigital.com/globalassets/resources/public/020-102560-02-christie-lit-tech-ref-gs-series-1075-api.pdf

Anyone got this working?

Thanks!

**Comment by isaiahfranco** [comment]
I would love to have feedback as well for my HD20K-J. Projector power and shutter status would be really helpful. It looks like the API for the J-Series projectors is about the same: https://www.christiedigital.com/globalassets/resources/public/020-100796-04-christie-lit-tech-ref-j-series-serial-commands.pdf

**Comment by isaiahfranco** [comment]
@krocheck @josephdadams Do either of you know if anyone is actively working on this module?

**Comment by josephdadams** [comment]
Not to my knowledge.

**Comment by greyshirtguy** [comment]
@josephdadams are you still a module dev "gun for hire"?
@isaiahfranco might consider that option if you are still available? (or not ¯\\\_(ツ)\_/¯ )

**Comment by josephdadams** [comment]
@greyshirtguy as often as possible. Put the word out for me, lol.

@isaiahfranco and I are already talking that through right now on slack. :)

**Comment by josephdadams** [comment]
shutter feedback is implemented now
