### ISSUE TITLE
One button for two state

### ISSUE THREAD

**Issue by mariospinaci** [bitfocus/companion-module-christie-projector#8]
Salutations,
I wanted to ask you if it was possible to create a button that would suit this example of mine.

Let's talk about projectors I currently have 3 buttons:
1) a button gives me the status of the projector shutter
2) a button closes the shutter
3) a button opens the shutter for me.

Well I would like it to be managed by a single button which has the status of the projector shutter as its label, and as an action it must open and close the shutter based on the previous status.

Thanks

**Comment by mariospinaci** [comment]
Therefore? wait for the update?

**Comment by josephdadams** [comment]
You could also try creating a latch button that closes it when you press it and opens it when you release it. However if you manipulated the shutter outside of Companion, this wouldn’t work.

**Comment by josephdadams** [comment]
> Therefore? wait for the update?

Wait for someone to code this for you. I’m available for hire to code this if you want to reach out to me via email (listed on my profile).

**Comment by mariospinaci** [comment]
Thanks for the informations...
I was hoping for a system not only for this module but in general for all situations where a button can have two states.

**Comment by mariospinaci** [comment]
Ok I have risolve with Latch... it's perfect

Thank You very much
